services:
  frontend-nginx:
    environment:
      NGINX_ENVSUBST_TEMPLATE_SUFFIX: .conf
    ports:
      - "80:80"
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /etc/nginx