name: 'Deploy Photo-Stock-Frontend'

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create .env file
        env:
          GQL_HOST: "http://persons-web-1.local/wp/graphql"
          APP_PORT: "4444"
        
        run: |
          touch .env
          echo "GQL_HOST=\"$GQL_HOST\"" >> .env
          echo "APP_PORT=\"$APP_PORT\"" >> .env


      - name: Build and run Docker containers
        run: |
          docker-compose -f docker-compose.prod.yml build
          docker-compose -f docker-compose.prod.yml down --rmi local --remove-orphans
          docker-compose -f docker-compose.prod.yml up -d

      - name: views logs
        run: |
          docker-compose logs -f photo-stock-frontend
          
